#!/bin/bash

echo "Creating boot partition..."
DEV=${1:-/dev/sda}

# Make BIOS Boot Partition (make certain /dev/sda is your actual block device!)
sgdisk --new=2:48:2047 --typecode=2:EF02 --change-name=2:"BIOS boot partition" $DEV

# Flush the page cache to ensure GRUB2 sees the latest disk content
echo 1 > /proc/sys/vm/drop_caches
touch /etc/mtab
