#!/bin/bash

echo "Beginning automated gentoo installation..."

# pool name is $1 or "tank"
POOL=${1:-tank}
# target device is $2 or "/dev/sda"
DEV=${2:-/dev/sda}

setup/zfs-prep $POOL $DEV 2>log

#copy scripts for future use...
cp -R . /mnt/gentoo/root/gentoo-install

setup/stage3
. ./chroot

# our scripts should be located in the /root/gentoo-install directory; continue from there
cd /root/gentoo-install

setup/portage-snapshot
setup/kernel-prep
setup/emerge-prereqs
setup/zfs-install
setup/boot-partition $DEV
setup/grub-install $DEV
setup/kernel-rebuild
setup/fstab-update
setup/emerge-utils
