#!/bin/bash

POOL=${1:-tank}
DEST=${2:-/mnt/gentoo}

echo "Importing zpool ${POOL} with alternate root ${DEST}"

zpool import -f ${POOL} -R ${DEST}

# create a new cachefile
zpool set cachefile=/tmp/zpool.cache ${POOL}